### ISSUE TITLE
和brv怎么结合，socketAdapter和brv冲突了把，一片混乱

### ISSUE THREAD

**Issue by walkthehorizon** [oubowu/StickyItemDecoration#19]

**Comment by jqorz** [comment]
> _No description provided._

我试了一下，适配器得用BaseSectionQuickAdapter，然后demo里的TYPE_STICKY_HEAD的值，用BaseSectionQuickAdapter里的SECTION_HEADER_VIEW。就可以了。

**Comment by ysy950803** [comment]
结合起来应该是没有难度的，这个控件本质上就是通过itemType来锁定的，所以只要保证BRV里面的itemType能对应上就行了。这里需要注意的是，如果你的BRV还添加了headerView，那么这个控件的setDataCallback方法回调的pos参数需要-1才能正确地getItem到相应数据，因为BRV的getItem方法获取的是data集合，不包括header和footer。
```java
StickyHeadContainer sHC = findViewById(R.id.my_list_shc);
TextView timeTitle = sHC.findViewById(R.id.my_time_title);
sHC.setDataCallback(pos -> {
    Object obj = listAdapter.getItem(pos - 1); // 有headerView，需-1
    if (obj instanceof TimeTitle) {
        TimeTitle data = (TimeTitle) obj;
        timeTitle.setText(data.getTitle());
    }
});
```
