### ISSUE TITLE
有瑕疵

### ISSUE THREAD

**Issue by feer921** [oubowu/StickyItemDecoration#7]
![image](https://user-images.githubusercontent.com/6622321/29512997-7a88d18e-8696-11e7-8cca-2c23d105d340.png)
当要滚动到最后一个分组“振幅榜”时，“振幅榜“并没有顶成 粘性头部，并且，与上一个换手率(此时它是粘性头部)连接了，见下图：
![image](https://user-images.githubusercontent.com/6622321/29513188-1f1ce640-8697-11e7-944c-b9d3770a4b83.png)

另：能与https://github.com/CymChad/BaseRecyclerViewAdapterHelper配合使用吗？

**Comment by oubowu** [comment]
1.那是因为振幅榜下面数据太少 你list都滑到尽头了 自然头部顶不上去
2.应该是可以滴
